import { Area, AreaChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
const colors = ["#3b82f6", "#8b5cf6", "#10b981", "#f59e0b", "#64748b"];
const duration = (study) => Number(study.actualDuration) || 0;
export default function ProfileAnalytics({ studies = [] }) {
  const today = new Date(); today.setHours(0, 0, 0, 0);
  const weekly = Array.from({ length: 7 }, (_, index) => { const date = new Date(today); date.setDate(today.getDate() - 6 + index); const seconds = studies.filter((study) => new Date(study.startTime || study.createdAt).toDateString() === date.toDateString()).reduce((sum, study) => sum + duration(study), 0); return { day: date.toLocaleDateString(undefined, { weekday: "short" }), hours: +(seconds / 3600).toFixed(2) }; });
  const distribution = studies.reduce((map, study) => { const date = new Date(study.startTime || study.createdAt); if (date.getMonth() === today.getMonth() && date.getFullYear() === today.getFullYear()) map[study.subject || "Other"] = (map[study.subject || "Other"] || 0) + duration(study); return map; }, {});
  const total = Object.values(distribution).reduce((sum, value) => sum + value, 0); const subjects = Object.entries(distribution).map(([name, value]) => ({ name, value: Math.round((value / total) * 100) }));
  const calendar = Array.from({ length: 49 }, (_, index) => { const date = new Date(today); date.setDate(today.getDate() - 48 + index); const seconds = studies.filter((study) => new Date(study.startTime || study.createdAt).toDateString() === date.toDateString()).reduce((sum, study) => sum + duration(study), 0); return { title: `${date.toLocaleDateString()} · ${(seconds / 3600).toFixed(1)}h`, level: seconds ? Math.min(4, Math.ceil(seconds / 3600)) : 0 }; });
  return <div className="grid gap-5 xl:grid-cols-3"><section className="rounded-3xl border border-slate-700 bg-slate-900 p-6 xl:col-span-2"><h2 className="font-bold text-white">Weekly Analytics</h2><p className="text-sm text-slate-400">Actual study hours for the last 7 days</p><div className="h-60"><ResponsiveContainer width="100%" height="100%"><AreaChart data={weekly}><CartesianGrid stroke="#334155" strokeDasharray="3 3" vertical={false}/><XAxis dataKey="day" stroke="#94a3b8"/><YAxis stroke="#94a3b8"/><Tooltip/><Area type="monotone" dataKey="hours" stroke="#3b82f6" fill="#3b82f655" strokeWidth={3}/></AreaChart></ResponsiveContainer></div></section><section className="rounded-3xl border border-slate-700 bg-slate-900 p-6"><h2 className="font-bold text-white">Monthly Subjects</h2><p className="text-sm text-slate-400">Study-time distribution</p>{subjects.length ? <><div className="h-52"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={subjects} dataKey="value" innerRadius={48} outerRadius={76}>{subjects.map((item, index) => <Cell key={item.name} fill={colors[index % colors.length]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div>{subjects.map((item) => <p key={item.name} className="text-xs text-slate-400">{item.name}: {item.value}%</p>)}</> : <p className="mt-16 text-center text-sm text-slate-400">No study data this month.</p>}</section><section className="rounded-3xl border border-slate-700 bg-slate-900 p-6 xl:col-span-3"><h2 className="font-bold text-white">Study Calendar</h2><p className="text-sm text-slate-400">Last 7 weeks of activity</p><div className="mt-5 grid grid-cols-7 gap-2 sm:grid-cols-14">{calendar.map((day, index) => <div key={index} title={day.title} className={`aspect-square rounded-md ${["bg-slate-800", "bg-blue-950", "bg-blue-800", "bg-blue-600", "bg-cyan-400"][day.level]}`}/>)}</div></section></div>;
}
